# -*- coding: utf-8 -*-
"""Saransh's Ultimate G7+ Economic Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-vu9DWLh4GdtFpP3YC2gupM1zbCg9OD
"""

# =====================================================================
# PROJECT: Saransh's Ultimate G7+ Economic Dashboard
# Skills: Data Science | Economics | Programming
# Features: 7 Indicators | 9 Countries | Dropdown Menu | Offline
# =====================================================================

# Install required packages (run this only once in Colab)
!pip install plotly pandas -q

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import numpy as np
import math
import random

# Set seed for reproducibility
random.seed(42)
np.random.seed(42)

# =====================================================================
# 1. DATA GENERATION ENGINE (Realistic World Bank-Style Data)
# =====================================================================
years = list(range(2000, 2024))

countries = [
    "United States", "United Kingdom", "France", "Germany",
    "Japan", "Italy", "Canada", "India", "China"
]

def generate_series(base, growth, cycle_amp, cycle_len, noise_amp):
    """Generates realistic economic time-series with trend, cycle, and noise."""
    series = []
    for i, year in enumerate(years):
        # Long-term trend
        trend = base + (growth * (i - 11) / 8)
        # Business cycle (sine wave)
        if cycle_len == 0:
            cycle = 0.0
        else:
            cycle = cycle_amp * math.sin((i / cycle_len) * 2 * math.pi)
        # Random noise
        noise = random.uniform(-noise_amp, noise_amp)
        val = trend + cycle + noise

        # Safety checks for non-negative indicators
        if base in [280, 60, 62, 82, 127, 57, 30, 1000, 1200] and val < 0:
            val = 0.1  # Population can't be negative
        elif base in [15, 10, 5, 1.5] and val < 0:
            val = 0.0  # Poverty can't be negative
        series.append(round(val, 2))
    return series

# =====================================================================
# 2. ECONOMIC PARAMETERS FOR EACH COUNTRY
# =====================================================================
params = {
    "United States": {
        "GDP": (2.0, 0.15, 2.5, 10, 0.5),
        "Inflation": (2.5, 0.1, 1.5, 12, 0.5),
        "Poverty": (1.5, -0.4, 0.3, 15, 0.2),
        "Education": (5.0, 0.0, 0.2, 20, 0.1),
        "Unemployment": (5.0, -0.1, 1.5, 8, 0.5),
        "Population": (280, 2.5, 0, 0, 0.5),
        "Trade": (-3.0, 0.1, 0.5, 10, 0.3)  # Negative = Trade Deficit
    },
    "United Kingdom": {
        "GDP": (2.0, 0.1, 2.0, 9, 0.5),
        "Inflation": (2.5, 0.0, 1.5, 11, 0.5),
        "Poverty": (1.5, -0.3, 0.2, 14, 0.2),
        "Education": (5.0, 0.0, 0.2, 18, 0.1),
        "Unemployment": (5.5, -0.1, 1.5, 7, 0.5),
        "Population": (60, 0.4, 0, 0, 0.1),
        "Trade": (-2.0, 0.0, 0.5, 9, 0.3)
    },
    "France": {
        "GDP": (1.5, 0.1, 1.8, 8, 0.4),
        "Inflation": (2.0, 0.0, 1.2, 10, 0.4),
        "Poverty": (1.5, -0.3, 0.2, 13, 0.2),
        "Education": (5.5, 0.0, 0.1, 20, 0.1),
        "Unemployment": (8.0, -0.1, 1.0, 6, 0.5),
        "Population": (62, 0.3, 0, 0, 0.1),
        "Trade": (-1.0, 0.1, 0.4, 8, 0.2)
    },
    "Germany": {
        "GDP": (1.5, 0.1, 2.0, 8, 0.4),
        "Inflation": (2.0, 0.0, 1.0, 10, 0.4),
        "Poverty": (1.0, -0.2, 0.2, 15, 0.1),
        "Education": (4.5, 0.0, 0.2, 18, 0.1),
        "Unemployment": (5.0, -0.2, 1.5, 8, 0.5),
        "Population": (82, 0.1, 0, 0, 0.1),
        "Trade": (5.0, -0.1, 1.0, 8, 0.4)  # Positive = Trade Surplus
    },
    "Japan": {
        "GDP": (1.0, 0.0, 1.5, 10, 0.4),
        "Inflation": (0.5, 0.1, 0.8, 12, 0.3),
        "Poverty": (1.0, -0.2, 0.2, 16, 0.1),
        "Education": (3.5, 0.0, 0.1, 20, 0.1),
        "Unemployment": (3.0, 0.0, 0.8, 9, 0.3),
        "Population": (127, -0.2, 0, 0, 0.1),
        "Trade": (2.0, 0.0, 0.5, 10, 0.3)
    },
    "Italy": {
        "GDP": (1.0, 0.0, 1.5, 9, 0.4),
        "Inflation": (2.0, 0.0, 1.0, 11, 0.4),
        "Poverty": (1.5, -0.2, 0.2, 14, 0.2),
        "Education": (4.0, 0.0, 0.1, 18, 0.1),
        "Unemployment": (10.0, -0.2, 1.5, 7, 0.5),
        "Population": (57, -0.1, 0, 0, 0.1),
        "Trade": (1.0, 0.0, 0.4, 9, 0.2)
    },
    "Canada": {
        "GDP": (2.0, 0.1, 2.0, 9, 0.5),
        "Inflation": (2.0, 0.1, 1.2, 11, 0.4),
        "Poverty": (1.0, -0.3, 0.2, 15, 0.2),
        "Education": (5.5, 0.0, 0.2, 19, 0.1),
        "Unemployment": (6.0, -0.1, 1.5, 8, 0.5),
        "Population": (30, 0.4, 0, 0, 0.1),
        "Trade": (-2.0, 0.1, 0.5, 8, 0.3)
    },
    "India": {
        "GDP": (6.0, 0.3, 3.0, 10, 0.8),
        "Inflation": (5.0, 0.0, 2.0, 10, 0.6),
        "Poverty": (15.0, -2.0, 2.0, 12, 0.5),
        "Education": (4.0, 0.1, 0.2, 15, 0.1),
        "Unemployment": (6.0, 0.0, 1.0, 8, 0.5),
        "Population": (1000, 12, 0, 0, 1),
        "Trade": (-2.0, 0.0, 0.5, 10, 0.3)
    },
    "China": {
        "GDP": (8.0, -0.2, 3.0, 10, 0.8),
        "Inflation": (2.0, 0.0, 1.5, 12, 0.5),
        "Poverty": (5.0, -1.5, 1.0, 10, 0.3),
        "Education": (3.5, 0.0, 0.2, 18, 0.1),
        "Unemployment": (4.0, 0.0, 0.8, 9, 0.3),
        "Population": (1200, 8, 0, 0, 1),
        "Trade": (3.0, -0.1, 1.0, 9, 0.4)
    }
}

# =====================================================================
# 3. GENERATE THE DATASET
# =====================================================================
data = {}
for country in countries:
    data[country] = {}
    for indicator in params[country].keys():
        p = params[country][indicator]
        data[country][indicator] = generate_series(*p)

# Map technical names to display titles
indicator_titles = {
    "GDP": "📈 GDP Growth (Annual %)",
    "Inflation": "💸 Inflation (Consumer Prices %)",
    "Poverty": "📉 Poverty Headcount ($2.15/day)",
    "Education": "📚 Education Spending (% of GDP)",
    "Unemployment": "👷 Unemployment Rate (%)",
    "Population": "👨‍👩‍👧‍👦 Total Population (Millions)",
    "Trade": "🌐 Trade Balance (% of GDP)"
}
indicator_keys = list(indicator_titles.keys())

# =====================================================================
# 4. BUILD THE DASHBOARD (7 Subplots)
# =====================================================================
fig = make_subplots(
    rows=7, cols=1,
    subplot_titles=list(indicator_titles.values()),
    vertical_spacing=0.06
)

# Add traces for all countries, default visible = United States
for row_idx, indicator in enumerate(indicator_keys):
    row = row_idx + 1
    for country in countries:
        fig.add_trace(
            go.Scatter(
                x=years,
                y=data[country][indicator],
                mode='lines+markers',
                name=country,
                visible=(country == "United States"),
                line=dict(width=2.5),
                marker=dict(size=5)
            ),
            row=row, col=1
        )

# =====================================================================
# 5. DROPDOWN LOGIC
# =====================================================================
def get_visibility(selected_country):
    """Returns a list of True/False for each trace (7 indicators * 9 countries)."""
    vis = []
    for _ in indicator_keys:  # 7 rows
        for country in countries:  # 9 countries
            vis.append(country == selected_country)
    return vis

buttons = []
for country in countries:
    buttons.append(
        dict(
            label=country,
            method="update",
            args=[
                {"visible": get_visibility(country)},
                {"title": f"🌍 Saransh's Global Economic Dashboard - {country} (2000-2023)"}
            ]
        )
    )

# =====================================================================
# 6. FINAL LAYOUT
# =====================================================================
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            showactive=True,
            x=0.5,
            y=1.12,
            xanchor="center",
            yanchor="top",
            font=dict(size=14),
            bgcolor="white",
            bordercolor="black",
            borderwidth=1
        )
    ],
    title_text="🌍 Saransh's Global Economic Dashboard - United States (2000-2023)",
    title_font_size=24,
    height=1600,
    showlegend=False,
    template="plotly_white",
    hovermode="x unified"
)

fig.update_xaxes(title_text="Year", row=7, col=1)
for i in range(1, 8):
    fig.update_yaxes(title_text="Value", row=i, col=1)

# =====================================================================
# 7. EXPORT AS OFFLINE HTML
# =====================================================================
fig.write_html("Saransh_G7_Economic_Dashboard.html")
print("✅ Dashboard built successfully!")

# Download the file (for Colab)
from google.colab import files
files.download("Saransh_G7_Economic_Dashboard.html")

print("\n" + "="*60)
print("🎉 DASHBOARD GENERATED!")
print("📁 File downloaded: Saransh_G7_Economic_Dashboard.html")
print("💡 Double-click the HTML file to open it in your browser.")
print("   Use the dropdown menu to switch between countries!")
print("="*60)